### ISSUE TITLE
"inverse" augmented data in EMNIST-DA dataset is missing

### ISSUE THREAD

**Issue by mingukjang** [cianeastwood/bufr#2]
I tried to download and use EMNIST-DA dataset. However, it is impossible to implement because there is no "inverse" augmented data. Can you re-upload the dataset?

**Comment by cianeastwood** [comment]
Thank you for pointing this out. We will re-upload the dataset and post a new link in the README tomorrow. In the meantime, you could remove "inverse" from the list in line 8 of configs/EMNIST-DA/dataset.yml.
